[package]
name = "rust_sorting"
version = "0.1.0"
authors = ["Max Fisher <max.fisher@keysight.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.7"
rayon = "1.5.0"

[profile.release]
debug = true